dse_api.settings: 
  type: config_object
  label: 'Configuration'
  mapping:
    url_list:
      type: sequence
      label: 'URLs'
      sequence:
          type: mapping
          label: 'URL + enabled'
          mapping:
            url_string:
              type: string
              label: 'URL'
            initialized:
              type: boolean
              label: 'Initialized'
            enabled:
              type: boolean
              label: 'Enabled'
            full_name:
              type: string
              label: 'Full name for resource'
